---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: uswiw470.kohlerco.com
      username: ko95056@kohlerco.com
      password: drkB4day*3
      validate_certs: False
      name: testvm_1
      template: RHEL7_Base
      datacenter: "Kohler Main"
      folder: "/Linux Servers"
      state: poweredon
      wait_for_ip_address: yes
