- hosts: localhost
  name: Remove virtual machine
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: ""
        datacenter: ""

    - name: Remove "{{ vm_name }}"
      vmware_guest:
        hostname: ""
        username: ""
        password: ""
        validate_certs: no
        cluster: ""
        name: "{{ vm_name }}"
        state: absent
      delegate_to: localhost
      register: facts
