- hosts: all
  vars:
    desired_state: "{{ chosen_state }}"
  tasks:
    # Handler showing how to clean yum metadata cache
    - name: yum-clean-metadata
      command: yum clean all
      args:
        warn: no
